In [4]:
import numpy as np

A= np.array(([56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]))

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [7]:
percentage=100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [13]:
B=np.array([1,2,3,4])
print(B)

[1 2 3 4]


In [15]:
sumB=B+100
print(sumB)

[101 102 103 104]


In [20]:
C=np.array(([1,2,3],[4,5,6]))
print(C)

[[1 2 3]
 [4 5 6]]


In [21]:
D=np.array([100,200,300])
print(D)

[100 200 300]


In [23]:
sumCD=C+D
print(sumCD)

[[101 202 303]
 [104 205 306]]


In [1]:
print("test")

test


In [3]:
print("teste123")

teste123
