In [2]:
import numpy as np 

a = np.random.randn(5)

print(a)

[-0.33560693  0.13742543  2.15757969  0.91536204  2.02551029]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.33560693  0.13742543  2.15757969  0.91536204  2.02551029]


In [5]:
print(np.dot(a,a.T))

9.727247480663786


In [6]:
# Create Vectors this way

a=np.random.randn(5,1)

print(a)

[[ 1.58558607]
 [-0.89211234]
 [ 0.39725859]
 [ 0.59899178]
 [-0.31059662]]


In [7]:
print(a.T)

[[ 1.58558607 -0.89211234  0.39725859  0.59899178 -0.31059662]]


In [8]:
print(np.dot(a,a.T))

[[ 2.51408319 -1.41452089  0.62988769  0.94975303 -0.49247768]
 [-1.41452089  0.79586442 -0.35439929 -0.53436796  0.27708708]
 [ 0.62988769 -0.35439929  0.15781439  0.23795463 -0.12338718]
 [ 0.94975303 -0.53436796  0.23795463  0.35879116 -0.18604482]
 [-0.49247768  0.27708708 -0.12338718 -0.18604482  0.09647026]]


In [10]:
a = np.array([[2,1],[1,3]])
print(np.dot(a,a))

[[ 5  5]
 [ 5 10]]
